# docker-compose.yml
version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: node
    restart: unless-stopped
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
  frontend-dev:
    container_name: frontend-dev
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 3000:3000
  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
      - 'http.host=0.0.0.0'
      - 'ES_JAVA_OPTS= -Xms512m -Xmx512m'
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
