# docker-compose.yml
version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  frontend:
    container_name: frontend
    image: node
    restart: unless-stopped
    build: .
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    volumes:
    - ./:/app
    - /app/node_modules
    ports:
      - 3000:3000
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: